### ISSUE TITLE
Sporadic blocking and unblocking of the requests

### ISSUE THREAD

**Issue by SyRenity** [AdamPflug/express-brute#17]
Encountered a strange behavior with same IP being randomly blocked / unblocked.

From the logs:
```
June 1st, 2015 [2015-06-01] 21:12:56.337 server1 INFO/request1 var1 var2 var3  clientIP
21:13:13.099 server2 INFO/request2 var1 var2 var3  clientIP
... tailing ...
June 1st, 2015 [2015-06-01] 21:14:00.371 server1 WARNClient sent too many requests, throttling IP  clientIP this request is  /request2
21:14:15.672 server2 INFO/request3 var1 var2 gem var3  clientIP
June 1st, 2015 [2015-06-01] 21:14:16.556 server2 INFO/request1 var1 var2 var3  clientIP
21:14:23.108 server2 INFO/request4 [{var4}] var3  clientIP
... tailing ...
June 1st, 2015 [2015-06-01] 21:14:31.015 server2 INFO/request4 [{var4}] var3  clientIP
... tailing ...
June 1st, 2015 [2015-06-01] 21:14:42.430 server2 INFO/request4 [{var4}] var3  clientIP
... tailing ...
June 1st, 2015 [2015-06-01] 21:15:00.500 server1 WARNClient sent too many requests, throttling IP  clientIP this request is  /request2
June 1st, 2015 [2015-06-01] 21:15:16.089 server2 INFO/request1 var1 var2 var3  clientIP
... tailing ...
June 1st, 2015 [2015-06-01] 21:16:00.938 server1 WARNClient sent too many requests, throttling IP  clientIP this request is  /request2
21:16:16.508 server2 INFO/request1 var1 var2 var3  clientIP
21:17:00.213 server1 WARNClient sent too many requests, throttling IP  clientIP this request is  /request2
21:17:15.866 server2 INFO/request1 var1 var2 var3  clientIP
21:18:13.038 server2 INFO/request4 [{var5}] var3  clientIP
```

The bruteforce settings are:

```
var genericBruteforce = new ExpressBrute(store, {
    freeRetries: 99,
    lifetime: 30,
    minWait: 31,
    maxWait: 31,
    attachResetToRequest: false,
    refreshTimeoutOnRequest: false,
    failCallback: someFn,
    handleStoreError: errorFn
});
```
The used Redis is Azure Redis caching service.

I've also tried erasing all the brute force keys from Redis, however once express-brute just recreates them, it starts the random blocking again.

Any idea what could be causing such behavior?

**Comment by AdamPflug** [comment]
I'm not sure I understand your log. What's the `... tailing ...` part? How are these requests being generated? Are there other requests not included in the log period you posted?

The settings you have there seem like they would work to have a maximum of 100 requests per IP, renewing every 30 seconds. That said, I notice that it looks like you have multiple servers running - if you had some kind of proxy or load balancer in front of your servers that was forwarding requests to the servers you would also need to set `proxyDepth` correctly. If you don't then ExpressBrute wont parse the `X-Forwarded-For` header and all requests will appear to it to be coming from the same IP as far as it is concerned.

**Comment by SyRenity** [comment]
Tailing is just the logging system showing there are no new logs for the periodic tail refresh (happening every 5 seconds or so), you can ignore it. The logs are filtered according to IP (marked as clientIP) with real requests details redacted out. These are all the requests originating from the said IP.

Good point about balancing, I do present the right IP in logs (req.headers['x-forwarded-for'] || req.connection.remoteAddress) however didn't have the option set on. Will check and update.

**Comment by SyRenity** [comment]
Apparently Azure load-balanced set keeps the client IP transparent (and doing stickiness on the way), at lest this what I see from testing:

```
app.get('/get-test', function(req, res) {
    winston.log('/get-test', 'x-forwarded', req.headers['x-forwarded-for'], 'remoteAddress', req.connection.remoteAddress);
    res.end();
});
```

/get-test x-forwarded  remoteAddress MY_CORRECT_IP

**Comment by AdamPflug** [comment]
Hmm, not sure quite what is happening here. I did clean up the log so it makes more sense to me:
```
21:12:56.337 server1 INFO/request1 var1 var2 var3  clientIP
21:13:13.099 server2 INFO/request2 var1 var2 var3  clientIP
21:14:00.371 server1 WARNClient sent too many requests, throttling IP  clientIP this request is  /request2
21:14:15.672 server2 INFO/request3 var1 var2 gem var3  clientIP
21:14:16.556 server2 INFO/request1 var1 var2 var3  clientIP
21:14:23.108 server2 INFO/request4 [{var4}] var3  clientIP
21:14:31.015 server2 INFO/request4 [{var4}] var3  clientIP
21:14:42.430 server2 INFO/request4 [{var4}] var3  clientIP
21:15:00.500 server1 WARNClient sent too many requests, throttling IP  clientIP this request is  /request2
21:15:16.089 server2 INFO/request1 var1 var2 var3  clientIP
21:16:00.938 server1 WARNClient sent too many requests, throttling IP  clientIP this request is  /request2
21:16:16.508 server2 INFO/request1 var1 var2 var3  clientIP
21:17:00.213 server1 WARNClient sent too many requests, throttling IP  clientIP this request is  /request2
21:17:15.866 server2 INFO/request1 var1 var2 var3  clientIP
21:18:13.038 server2 INFO/request4 [{var5}] var3  clientIP
```
One thing that stands out is that all the requests to server 2 succeed, and all but the first request to server 1 fail. Is it possible that the same version of the code isn't on both versions? Like maybe if server1 using MemoryStore? Do you still have issues with only one server? Does this behavior persist over a longer log session?

**Comment by SyRenity** [comment]
It's same git tag.

The issue is happening during longer sessions as well.

I've temporary disabled as it a production system, will re-enable and
update.

**Comment by AdamPflug** [comment]
When I say during longer sessions I mean is the server1/server2 difference consistent with a larger sample size - or was that just a coincidence?

**Comment by AdamPflug** [comment]
Closing this for now. Re-open if you have more info.
