### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by globlee** [AdamPflug/express-brute#21]
If you can tell me what likely caused this I can try to fix it myself and do a pull request. I do not know what the error  in the title actually means.

Relevant code:

var store = new MongoStore(function (ready) {
      MongoClient.connect('mongodb://localhost/globlee', function(err, db) {
            if (err){ 
                console.log(err);
            } else{
                ready(db.collection('bruteforce-store-vendor'));
            }
      });
});

var failCallback = function (req, res, next, nextValidRequestDate) {
    res.send("Too many failed attemps. Try again in: "+moment(nextValidRequestDate).fromNow());
};
var handleStoreError = function (error) {
    console.log.error(error);
}
var userBruteforce = new ExpressBrute(store, {
        freeRetries: 5,
        proxyDepth: 1,
        minWait: 5*60*1000, // 5 minutes 
        maxWait: 60*60*1000, // 1 hour, 
        failCallback: failCallback,
        handleStoreError: handleStoreError
});

var globalBruteforce = new ExpressBrute(store, {
    freeRetries: 1000,
    proxyDepth: 1,
    attachResetToRequest: false,
    refreshTimeoutOnRequest: false,
    minWait: 25*60*60*1000, // 1 day 1 hour (should never reach this wait time) 
    maxWait: 25*60*60*1000, // 1 day 1 hour (should never reach this wait time) 
    lifetime: 24*60*60, // 1 day (seconds not milliseconds) 
    failCallback: failCallback,
    handleStoreError: handleStoreError
});

 router.post('/v/login', globalBruteforce.prevent,
    userBruteforce.getMiddleware({
        key: function(req, res, next) {
            next(req.body.website);
        }
    }), login, function(req,res){
        console.log("this was called!!") //happens after login middleware completes
		                req.brute.reset(function () {
                                    res.redirect('/v');
                                    //return next();
                                });
    });

![screenshot 17](https://cloud.githubusercontent.com/assets/10442269/8245908/9f593edc-1603-11e5-956c-2845ec972947.jpg)
![screenshot 16](https://cloud.githubusercontent.com/assets/10442269/8245916/aa02a490-1603-11e5-8513-cfba7868c697.jpg)

If you would like me to use a debug tool like gnu debugger, I can do so.

debug log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart globlee@0.0.0
6 info start globlee@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info globlee@0.0.0 Failed to exec start script
9 verbose stack Error: globlee@0.0.0 start: `node ./bin/www`
9 verbose stack Exit status 139
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1008:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
10 verbose pkgid globlee@0.0.0
11 verbose cwd /home/ubuntu/proj/globlee
12 error Linux 3.13.0-36-generic
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v0.12.0
15 error npm  v2.5.1
16 error code ELIFECYCLE
17 error globlee@0.0.0 start: `node ./bin/www`
17 error Exit status 139
18 error Failed at the globlee@0.0.0 start script 'node ./bin/www'.
18 error This is most likely a problem with the globlee package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./bin/www
18 error You can get their info via:
18 error     npm owner ls globlee
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by AdamPflug** [comment]
Looks like a lot of the console log image is missing. That said, my understanding is that segmentation faults are usually caused by trying to access memory you don't have permission to read (which shouldn't be possible in node unless you a leveraging native libraries).

It seems unlikely that this is an express-brute problem, but can you tell what line is causing the error?

**Comment by globlee** [comment]
req.brute.reset(function () {
});

causes the crash. hmm.

**Comment by globlee** [comment]
Nothing relevant is missing from the image, I took it to show that right after the "this was called" is logged it crashes. Without the brute.reset it does not crash.

**Comment by globlee** [comment]
I will try to fix it some more and report back

**Comment by AdamPflug** [comment]
Maybe try https://github.com/ddopson/node-segfault-handler to get a stack trace? What version of node are you using?

**Comment by globlee** [comment]
Ok I think this was caused by something else, I modified a lot of my login code and now it is not happening. Sorry about that, I just thought that since it crashed right after logging that message it must be the cause. For some reason it also stopped happening before without the brute.reset, but maybe I modified something else with it.
