### ISSUE TITLE
Make getMiddleware able to read status of other route

### ISSUE THREAD

**Issue by deveshsinghal22** [AdamPflug/express-brute#28]
Hi, 

I was using this awesome plugin. I have a query regarding this. can we check the status of another route in getMiddleware. 
for eg if I want to check the status in 'GET /login' that 'POST /login' is facing an attack and get blocked.

**Comment by AdamPflug** [comment]
I'm working on a longer-term project to pull out some of the core of express-brute into another project, so I can make a similar middleware for koa. Part of that will expose this kind of thing more directly if you need it... but like I said it's a longer term project.

In the short term I think the thing to do would be just to use connect-flash in the error handler to set a session variable indicating the error, then display that on the GET to /login. That make sense?

**Comment by deveshsinghal22** [comment]
Yeah @AdamPflug 

But session will not accessible in private browsing.

**Comment by AdamPflug** [comment]
Cookie-based sessions should work fine even in private browsing modes. They wont persist between the private mode and public mode, or between private sessions, but it will still work fine for moving error data from one page to the next. Alternatively, you could use query string based sessions that will work no matter what.
