### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by ganna-shmatova** [AdamPflug/express-brute#31]
Not the first time I'm implementing this so a little odd...

```js
var expressBrute = require('express-brute');
var bruteProtection = new expressBrute(new expressBrute.MemoryStore(), {
	freeRetries: 2,
	minWait: 5*60*1000, // 5 minutes
	maxWait: 60&60&1000, // 1 hour
});
app.all('/login', bruteProtection.prevent, function(req, res, next){
	log.trace('calls login');
	next();
});
```

However, it just keeps returning 401 (because I made login fail) -- no 429. I can't get it to ring 429 even once.

I've put this code at the beginning of my express/app stack and still no-go. Above it loads views/view engine of jade, sets static paths for js/css serving, morgan, and express session.

I'm not sure how to debug this.

**Comment by AdamPflug** [comment]
You may have already figured this out, but I think the issue you're running into is the typo on line 5. `60&60&1000` should be `60*60*1000`. `60&60&1000` is equal to `40` ms (bitwise and).

**Comment by ganna-shmatova** [comment]
... I have not, and I much appreciate the extra set of eyes. I feel silly. it works now.
