### ISSUE TITLE
Express deprecated

### ISSUE THREAD

**Issue by hckhanh** [AdamPflug/express-brute#34]
When I use this module, I receive this warning. I think you should fix it.

```sh
express deprecated res.send(status, body): Use res.status(status).send(body) instead node_modules\express-brute\index.js:163:6
```

**Comment by AdamPflug** [comment]
That should have been fixed in v0.5.2, can you confirm you're using the latest version?

**Comment by hckhanh** [comment]
Hi @AdamPflug,
I am using v0.5.0. I will upgrade to v0.6 now. Thank you :+1:

**Comment by hckhanh** [comment]
I remember that the express-brute-mongo has the problem with express-brute

```bash
npm WARN express-brute-mongo@0.1.0 requires a peer of express-brute@~0.5.0 but none was installed.
```

**Comment by AdamPflug** [comment]
I would open a bug for that on the express-brute mongo repository, since I don't own that.
