### ISSUE TITLE
performance concern

### ISSUE THREAD

**Issue by mauvew** [AdamPflug/express-brute#41]
Thanks for creating this great plugin.

Just wondering that by adding this middleware to express, what would be the affect of the request handling performance? I mean, is it going to delay the speed of server side working? Thanks.

**Comment by AdamPflug** [comment]
It has a small performance impact if you're running it with a backend (since it adds a cache query or two), but it shouldn't really be noticeable. If it's preventing DOS or brute force password attacks though it should definitely be a net performance improvement.
