### ISSUE TITLE
Is there a way to retrieve the IP

### ISSUE THREAD

**Issue by lel1234** [AdamPflug/express-brute#43]
Hello and thanks for this module,

I'm wondering if there is a way to get the IP and put it in the database next to the other data?

I'm using the express-brute-mongoose store with this schema (if that's relevant) : 

    var bruteForceSchema = mongoose.Schema({
    _id: { type: String, index: 1 },
    data: {
        count: Number,
        lastRequest: Date,
        firstRequest: Date
    },
    expires: { type: Date, index: { expires: '1d' } }
    });

**Comment by AdamPflug** [comment]
You can get the IP with `req.ip` in express. It's not stored directly in the DB (though it is used to generate the key). If you wanted to log rejections, you can use `failCallback: function(req) { log(req.ip); }` instead.

**Comment by lel1234** [comment]
Ok thanks !
