### ISSUE TITLE
add new express-brute-couchbase store

### ISSUE THREAD

**Issue by kvaillant** [AdamPflug/express-brute#44]
Hi, 
I realized a new store modules for express-brute on couchbase store.
Thank you for adding it in your docs.
You made a great job !

`https://www.npmjs.com/package/express-brute-couchbase`

**Comment by AdamPflug** [comment]
Not sure what the ask is here, but I think express-brute should be a [Peer Dependency](https://nodejs.org/en/blog/npm/peer-dependencies/) instead of a normal dependency of your package.

**Comment by kvaillant** [comment]
Thank you, I move to `peerDependencies`.
