### ISSUE TITLE
Does this module work properly behind nginx and cloudflare?

### ISSUE THREAD

**Issue by lel1234** [AdamPflug/express-brute#47]
How does express-brute exactly work? Since cloudflare use their own IPs to make request to a website, will this module still work?

Thanks

**Comment by AdamPflug** [comment]
If the trust proxy setting in express is set correctly then it should work. 

http://expressjs.com/en/api.html#trust.proxy.options.table

**Comment by lel1234** [comment]
Completely forgot about that, thanks!
