### ISSUE TITLE
Can we use a custom key to identify the number of requests per endpoint?

### ISSUE THREAD

**Issue by shriramshankar** [AdamPflug/express-brute#50]
I was wondering if we could use a custom key to identify the numbers of requests instead of the IP ?

**Comment by andrewholsted** [comment]
We were looking at this too. It seems there is an option for it, but the options are not passed to the `getMiddleware()` function (line 34, index.js). Is that correct? We're looking at adding this.options to _.extend on line 36.

**Comment by ChrisCinelli** [comment]
Any news on this?

**Comment by AdamPflug** [comment]
There is an `ignoreIP` option, as well as a custom `key` option for `getMiddleware(options)` - combined I think these let you do exactly this - or is there something I'm missing about this request?

@andrewholsted You can re-use the same middleware across multiple requests:
```javascript
var store = new ExpressBrute.MemoryStore();
var bruteforce = new ExpressBrute(store);
var preventBruteforce = bruteforce.getMiddleware({
	ignoreIP: true,
	key: function (req, res, next) {
		return: req.user.id;
	}
});
app.post('/auth',
	preventBruteforce, // rate limit for each user, regardless of IP
	function (req, res, next) {
		res.send('Success!');
	}
);
```
