### ISSUE TITLE
Errors are not handled correctly

### ISSUE THREAD

**Issue by achallett** [AdamPflug/express-brute#52]
Using the recommended express-brute-mongo addition, the node server will crash in the event that node loses connection with the IP logging table. There doesn't appear to be a way to catch the errors. 
For example; A user makes a call to the node js server causing it to crash in the event that the server loses connection to the IP address store.

**Comment by AdamPflug** [comment]
It should call `handleStoreError` (the default implementation of which is to throw an unhandled exception I think...)  if it's not then that sounds like a bug with express-brute-mongo.
