### ISSUE TITLE
What data is stored?

### ISSUE THREAD

**Issue by bryanCoteChang** [AdamPflug/express-brute#58]
Firstly, express-brute is awesome! 

Secondly, potentially stupid question, but I wanted to confirm what data express-brute stores.  Is it just ip/timestamp or is it the entire request/parameters?

My concern is that if I put this in front of a PCI/PII/login related endpoint, I could be exposing sensitive information in my environment.  

Not a big deal if I it is, I'm assuming if it does, should I just remove extraneous info and hash potentially relevant sensitive data?

**Comment by bryanCoteChang** [comment]
Alright, for those of those interested here is what I've found while using express-brute-redis:
Key is a sha 256 hash of:
- IP
- ExpressBrute instance count.  IE: "brute1"
- Key (if declared)
Value is:
- Count of requests
-Datetime of last request
-Datetime of first request

Looks fairly compliant to me!  Please let me know if there's anything else I should know about though.

**Comment by AdamPflug** [comment]
That about covers it, the one exception is that if you provide a key function it just uses the value you return (so it would be possible to pass sensitive data in via that).
