### ISSUE TITLE
"Too many requests" for successful logins

### ISSUE THREAD

**Issue by ManuZenou** [AdamPflug/express-brute#60]
Hi,

I'm using this middleware for my login API, I noticed that it blocks me after X successful login. 
is there a way to reset the count after a successful login?

Thanks.

**Comment by ManuZenou** [comment]
I have managed to do so by using the `reset(ip, key, callback) `function manually.
Thanks anyway.

**Comment by AdamPflug** [comment]
Sorry for the slow reply.

For future reference, you can just call `req.brute.reset(callback)` - Express Brute attaches that function to the request object (assuming `options.attachResetToRequest` is not false) to make it easy to do this exact thing. Also, in you have multiple express brute instances for a request this takes care of resetting them all for you (so you don't need to do it for each one individually).

See the "more complex example" in the readme.
