### ISSUE TITLE
import * as ExpressBrute from 'express-brute' - How to use in typescript

### ISSUE THREAD

**Issue by Thavaprakash** [AdamPflug/express-brute#71]
How to use in typescript

import * as ExpressBrute from 'express-brute'

i try to access ExpressBrute.defaults.maxWai , but getting below error

[ts] Property 'defaults' does not exist on type 'typeof ExpressBrute'

**Comment by knor-el-snor** [comment]
I use it in typescript, and it works as intended.
Why do you need to access the defaults? Looking at the source code, the defaults are automatically used and overwritten by your provided options.

**Comment by Thavaprakash** [comment]
I'm using below code, if i'm not getting from user input then i would set defaults. Is it make sense?

          const rateLimits = request.rateLimits;
          const bruteForce = new ExpressBrute(store, {
            freeRetries:
              rateLimits.freeRetries === undefined
                ? ExpressBrute.defaults.freeRetries
                : rateLimits.freeRetries,
            minWait:
              rateLimits.minWait === undefined
                ? ExpressBrute.defaults.minWait
                : rateLimits.minWait,
            maxWait:
              rateLimits.maxWait === undefined
                ? ExpressBrute.defaults.maxWait
                : rateLimits.maxWait
           });

**Comment by knor-el-snor** [comment]
The defaults are not placed onto the prototype of the ExpressBrute or MemoryStore, so it's logical you can't use them. But seeing that it will use the defaults internally, and only overwrite the ones you provide, I propose to filter out the undefined values in the properties you pass to ExpressBrute.

```
const request = {
    rateLimits: {
        freeRetries: undefined,
        minWait: undefined,
        maxWait: undefined,
    }
};

// Trick to filter out undefined values from an object (other cleaner ways are maybe available...)
const rateLimits = JSON.parse(JSON.stringify(request.rateLimits));
const bruteForce = new ExpressBrute(store, rateLimits);

This will use the default value per key if it is not provided (undefined)
```
