### ISSUE TITLE
Allow to get IP from X-Forwarded-For header

### ISSUE THREAD

**Issue by erasmo-marin** [AdamPflug/express-brute#78]
I'm running my app in AWS with a load balancer. The load balancer overwrites the IP header in req.ip, so, if express-brute locks a request, it will be locked for all clients. I need a way to get the IP from X-Forwarded-For header. I have a middleware that does this:

`const clientIp = req.get("X-Forwarded-For") || req.connection.remoteAdress;`

Is it possible to add an option to use this IP instead the IP in req.ip?

**Comment by erasmo-marin** [comment]
Yeah I know that the header can be overwritten, but it's always possible for me to get the last ip in the chain, which will be the real ip. A whitelist is not an option for us since the proxy ip is not predictable, the infrastructure is created and scaled on demand, so the load balancer ip changes.

Maybe add an option to pass a function to get the ip any way the user want? something like this:

```
var bruteforce = new ExpressBrute(expressBruteStore, {
    freeRetries: 3,
    minWait: 1000,
    maxWait: 10000,
    lifetime: 30,
    getIp: req => (req.get("X-Forwarded-For") || req.connection.remoteAdress || req.ip)
});
```

**Comment by AdamPflug** [comment]
I think the behavior you're asking for is provided by this:
```javascript
app.set('trust proxy', 1);
```

**Comment by fnaquira** [comment]
> 
> 
> I think the behavior you're asking for is provided by this:
> 
> ```js
> app.set('trust proxy', 1);
> ```

This should be added to the documentation.
