### ISSUE TITLE
`nextValidRequestTime` is incorrect in `failCallback`?

### ISSUE THREAD

**Issue by nguymin4** [AdamPflug/express-brute#84]
Hi @AdamPflug, I have trouble to understand the `nextValidRequestTime` in `failCallback`
Let's say I have this config
```
new ExpressBrute(store, {
    freeRetries: 5,
    minWait: 5000,
    maxWait: 5000
});
```
The current implementation has `delays = [5000]`, `lifetime = 30`.
Current behavior:
`failCallback` returns `nextValidRequestTime` is `lastValidRequestTime + 5 seconds` (delay = maxWait)

Expected behavior:
`failCallback` should return `nextValidRequestTime` is `lastValidRequestTime + 30 seconds`.
Because I try to request again 5 seconds after the last request, the request will be stopped. But after 30 seconds after the last request, the request will go through.

Am I missing something here? Thanks.

**Comment by AdamPflug** [comment]
`nextValidRequestTime` is determined by the min/max wait and the number of previous tries, not by lifetime. So after your first requests (6 in this case), you can issue a request every 5 seconds. `lifetime` is basically how long the store will remember each session, as way to prevent the store from filling up with a bunch of old sessions. After `lifetime` (30 seconds in this case), express-brute basically forgets about the user and they get a new set of free retries (again, 6 more requests) before being rate limited again.

By default it's calculated such that there isn't a benefit for waiting until the lifetime expires to issue new request. In this case if you wait 30 seconds you get 6 requests before the rate limiting kicks in, which is the same number of requests you'd get in the 30 second period if you just tried every 5 seconds (as specified by max/min wait).

You can manually set lifetime if you want, which can be useful if you want to limit the number of requests in a specific timeframe. For example, this limits the user to 10 requests every minute (the minute starts counting from the first request):
```javascript
var tenRequestsPerMinute = new ExpressBrute(store, {
	freeRetries: 10,
	refreshTimeoutOnRequest: false,
	minWait: 61*1000, // 61 seconds (we will never reach this wait time)
	maxWait: 61*1000, // 61 seconds (we will never reach this wait time)
	lifetime: 60 // 60 seconds (in seconds not milliseconds)
});
```

Let me know if that answers your question
-Adam

**Comment by nguymin4** [comment]
I understood your example. 
However, in my case, let's say I set up my endpoint like this with the config I specified above.
`router.post('/', expressBruteMiddleware, (req, res, next) => {})`

So at the moment if I send 6 requests consecutively:
- The first 5 requests will go through. 
- On the 6th request, `expressBruteMiddleware` will step in and throw error - which is as expected. 
But the value `nextValidRequestTime` which is returned by fail `failCallback` doesn't indicate the next time I can send another request and it goes through. 
In fact, I can successfully send another request after 30 seconds (lifetime) after 6th request.

Hopefully you understand my question now. Thanks you Adam.

**Comment by AdamPflug** [comment]
I'm not sure I understand. Are you saying that if you get rate limited, then wait 6 seconds and try again it doesn't work, you need to wait the full 30 for the lifetime to expire? The time that nextValidRequestTime is reporting should be correct, so that wouldn't be the correct behavior. That's unexpected because this is case that should be covered by the unit tests, which store are your using?

**Comment by nguymin4** [comment]
I use `express-redis-store`. I was tinkering around with your unit tests and they work as I expected. 

I think I know what is problem. I have one ExpressBrute instance and its `expressBruteMiddleware` is used in 2 different endpoints `GET /foo` `GET /bar`.
Front-end tries to `GET /foo` and `GET /bar` one after another from back-end, and here comes the problem. 

So my guess is that I probably need to create different instances and different prefixes for those endpoints :thinking: 

Thank you for your support. We can close the issue now.
